version: "3.8"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: recibeira
    ports:
      - 3306:3306
  adminer:
    image: adminer
    container_name: mysql_admin
    ports:
      - 8080:8080
  web:
    image: fusrodah061/gerador-recibo
    container_name: gerador-recibo
    build: .
    depends_on:
      - mysql
    env_file: .env
    ports:
      - 3333:3333
    environment:
      - DB_HOST=mysql:3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=recibeira
      - COMPOSER_ALLOW_SUPERUSER=1
